config/routes.rb
Rails.application.routes.draw do
	resources :terms
	root 'terms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/term.rb
class Term < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
before_action :find_term, only: [:show, :edit, :update, :destroy]

	def index
		@terms = Term.all.order("created_at DESC")
	end

	def show
	end

	def new
		@term = Term.new
	end

	def create
		@term = Term.new(term_params)
		@term.signed_on = Time.now.in_time_zone('Seoul')
		if @term.save
     		 redirect_to root_url, notice: 'Terms and Conditions accepted.'
		else
			render 'new'
		end
	end

	private

		def term_params
			params.require(:term).permit(:name, :signature, :signed_on, :check)
		end

		def find_term
			@term = Term.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/terms/index.html.erb
<div class="container" style="margin-top:30px;">
	<CENTER>
	<h3>서명된 모든 MRI 동의서</h3>
	<%= link_to "새로운 동의서작성", new_term_path %>
	</CENTER>


<div class="container" style="margin-top: 50px;">
<%= @terms.each do |t| %>
<div style="margin-left:80px;">
	<h4><%= t.name %> </h4>
	<%= link_to "동의서 보기", term_path(t) %>
	<hr>
</div>
<% end %>
</div>


</div>

app/views/terms/new.html.erb
<%= render 'form' %>